(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2019-06-04 14:21:40
  From session:  dnd
  Captured on:  2019-06-04 14:20:26
  From server:  TestServer
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

KeyDown ControlKey
KeyUp ControlKey
Drag "PD_PBSJobApp_Page/image0001"
Drop "PD_PBSJobApp_Page/image0002"

moveto "PD_Created_Profiles/Lable_NewPro", "PD_Created_Profiles/Lable_NewPro"

put ImageFound(5, (text:"NewProND"))